### ISSUE TITLE
Upgrade asciitable for numpy compatibility

### ISSUE THREAD

**Issue by rickyegeland** [ktindiana/fetchsep#10]
Reported by Lei Cheng (SEPSAT)  Traceback is self explanetory.  Appears to be a dependency mismatch between asciitable and numpy.

```
Traceback (most recent call last):
  File "/udrive/staff/lcheng/.local/bin/opsep_batch", line 4, in <module>
    import fetchsep.opsep.batch_run_opsep as batch
  File "/udrive/staff/lcheng/.local/lib/python3.9/site-packages/fetchsep/opsep/batch_run_opsep.py", line 13, in <module>
    import asciitable
  File "/udrive/staff/lcheng/.local/lib/python3.9/site-packages/asciitable/__init__.py", line 29, in <module>
    from asciitable.core import (has_numpy,
  File "/udrive/staff/lcheng/.local/lib/python3.9/site-packages/asciitable/core.py", line 735, in <module>
    class NumpyOutputter(BaseOutputter):
  File "/udrive/staff/lcheng/.local/lib/python3.9/site-packages/asciitable/core.py", line 768, in NumpyOutputter
    default_converters = [convert_numpy(numpy.int),
  File "/udrive/staff/lcheng/.local/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When eplacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additonal information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    [https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnumpy.org%2Fdevdocs%2Frelease%2F1.20.0-notes.html%23deprecations&data=05%7C01%7Cricky.a.egeland%40nasa.gov%7Cdd91c502ac2142b9c8a408dbd6fedd45%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638340162337869940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=56UtMqwLzadT%2BvaDBrRTXRvooFDUc5Y%2B6NDI70fv2uI%3D&reserved=0)
```

**Comment by ktindiana** [comment]
Removed the asciitable module from batch_run_opsep.py. It wasn't needed.
